"""Card Acquisition Funnel — BI dashboard (Phase 1).

Three views over the governed analytics marts:
  * Adoption vintage curves  — cumulative adoption rate by msa, one line per cohort.
                               Right-censored cells shown as dashed lines or hidden.
  * Funnel waterfall         — acquired → adopted → retained (3m), stage counts.
  * Cohort x segment heatmap — adoption_rate by (acq_month x segmento), fully-observed.

Reads only the small aggregated marts, never raw source tables.
"""
from __future__ import annotations

import sys
from pathlib import Path

import plotly.express as px
import plotly.graph_objects as go
import streamlit as st

# App dir + repo root on path so `queries` resolves when run via
# `streamlit run app/main.py` and the governed `semantic` layer imports as the single
# source of truth shared with the copilot/agents (rather than being redefined here).
sys.path.insert(0, str(Path(__file__).resolve().parent))
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import requests  # noqa: E402

from config import COPILOT_API_URL  # noqa: E402
from queries import (  # noqa: E402
    load_adoption_curves,
    load_cohort_heatmap,
    load_funnel_counts,
    load_latest_digest,
)
from semantic import list_metrics  # noqa: E402

st.set_page_config(
    page_title="Card Acquisition Funnel",
    page_icon=None,
    layout="wide",
)

st.title("Card Acquisition Funnel")
st.caption(
    "Acquisition → adoption → retention analytics on the Santander Product Recommendation "
    "panel (Kaggle 2016). Within-panel acquirees only (~155k). "
    "Left-censored customers excluded (0.06%). Monthly retention granularity. "
    "Public/synthetic data — see repository data footer."
)

with st.expander("Governed metric definitions (semantic layer)"):
    st.caption(
        "Every chart and every copilot answer computes these metrics — defined once in "
        "the governed semantic layer, text-to-metric never text-to-SQL. Windows use the "
        "MSA (months-since-acquisition) vocabulary."
    )
    st.dataframe(
        [
            {
                "Metric": m["label"],
                "Definition": m["description"],
                "Unit": m["unit"],
                "Valid windows": ", ".join(m["valid_windows"]),
            }
            for m in list_metrics()
        ],
        hide_index=True,
        use_container_width=True,
    )

# ── Insight of the month (proactive digest) ──────────────────────────────────────
# Pre-generated in Airflow after dbt, gated by the deterministic critic + numeric-
# faithfulness check, and served from mart_digest_cache at $0. Only a critic-passed,
# faithful digest is ever cached — so every number here was signed off in code.
_digest = load_latest_digest(window="msa_6")
if _digest is not None:
    with st.container(border=True):
        st.subheader("Insight of the month")
        st.caption(
            f"Latest fully-observed cohort {_digest['cohort_month']} · window {_digest['window']} · "
            f"{_digest['material_findings']} material finding(s) · "
            "auto-generated, critic-gated, numerically verified"
        )
        st.markdown(_digest["prose"])
        st.caption(
            "Generated by the proactive multi-agent digest (planner → parallel analysts → "
            "deterministic critic → narrator). The narrator may only restate figures the "
            "critic approved; any invented number blocks caching and flags the digest for review."
        )

vintage_tab, funnel_tab, heatmap_tab, copilot_tab = st.tabs(
    ["Adoption vintage curves", "Funnel waterfall", "Cohort × segment heatmap", "Ask the copilot"]
)


# ── Visual 1: Adoption vintage curves ────────────────────────────────────────────
with vintage_tab:
    df = load_adoption_curves()

    left, right = st.columns([1, 3])
    with left:
        all_cohorts = sorted(df["acq_month_label"].unique())
        default_cohorts = all_cohorts  # show all by default; user can filter
        cohorts = st.multiselect(
            "Acquisition cohorts",
            all_cohorts,
            default=default_cohorts,
            help="Select cohorts to plot. Each line = one acquisition-month cohort.",
        )
        observed_only = st.checkbox(
            "Fully-observed cells only",
            value=False,
            help=(
                "When checked, hide right-censored MSA points "
                "(cells where the cohort had insufficient panel time). "
                "When unchecked, censored cells are shown as dashed lines."
            ),
        )
        max_msa = st.slider(
            "Max MSA to display",
            min_value=1,
            max_value=int(df["msa"].max()),
            value=int(df["msa"].max()),
        )

    with right:
        if not cohorts:
            st.info("Select at least one cohort in the sidebar.")
        else:
            view = df[df["acq_month_label"].isin(cohorts) & (df["msa"] <= max_msa)]

            if observed_only:
                view = view[view["fully_observed_n"]]
                fig = px.line(
                    view,
                    x="msa",
                    y="adoption_rate",
                    color="acq_month_label",
                    labels={
                        "msa": "Months since acquisition (MSA)",
                        "adoption_rate": "Cumulative adoption rate",
                        "acq_month_label": "Acquisition cohort",
                    },
                    title="Cumulative card-adoption rate by MSA — fully-observed cells",
                )
            else:
                # Separate observed vs censored for visual distinction
                observed = view[view["fully_observed_n"]]
                censored = view[~view["fully_observed_n"]]

                fig = px.line(
                    observed,
                    x="msa",
                    y="adoption_rate",
                    color="acq_month_label",
                    labels={
                        "msa": "Months since acquisition (MSA)",
                        "adoption_rate": "Cumulative adoption rate",
                        "acq_month_label": "Acquisition cohort",
                    },
                    title="Cumulative card-adoption rate by MSA",
                )
                # Overlay right-censored tails as dashed grey lines
                cohort_colors = {
                    trace.name: trace.line.color
                    for trace in fig.data
                    if hasattr(trace, "line")
                }
                added_legend = set()
                for cohort, grp in censored.groupby("acq_month_label"):
                    show_in_legend = cohort not in added_legend
                    fig.add_trace(
                        go.Scatter(
                            x=grp["msa"],
                            y=grp["adoption_rate"],
                            mode="lines",
                            line=dict(dash="dash", color="rgba(150,150,150,0.6)"),
                            name="Right-censored (lower bound)",
                            legendgroup="censored",
                            showlegend=show_in_legend,
                        )
                    )
                    added_legend.add(cohort)

            fig.update_yaxes(tickformat=".1%")
            fig.update_xaxes(dtick=1)
            st.plotly_chart(fig, use_container_width=True)
            st.caption(
                "Solid lines: fully-observed cells. "
                "Dashed grey: right-censored MSA points — cohort did not have enough "
                "panel time; these are lower bounds, not final adoption rates. "
                "Toggle 'Fully-observed cells only' to hide them."
            )


# ── Visual 2: Funnel waterfall ────────────────────────────────────────────────────
with funnel_tab:
    fdf = load_funnel_counts()
    acquired = int(fdf["acquired"].iloc[0])
    adopted = int(fdf["adopted"].iloc[0])
    retained = int(fdf["retained_3m"].iloc[0])

    k1, k2, k3, k4 = st.columns(4)
    k1.metric("Acquired (panel cohort)", f"{acquired:,}")
    k2.metric("Adopted (clean)", f"{adopted:,}", delta=f"{adopted / acquired:.1%} of acquired")
    k3.metric(
        "Retained (3m)",
        f"{retained:,}",
        delta=f"{retained / adopted:.1%} of adopted" if adopted else "—",
    )
    k4.metric(
        "Overall adoption rate",
        f"{adopted / acquired:.1%}" if acquired else "—",
    )

    stages = ["Acquired", "Adopted", "Retained 3m"]
    counts = [acquired, adopted, retained]
    pcts = [
        "100%",
        f"{adopted / acquired:.1%}" if acquired else "—",
        f"{retained / acquired:.1%}" if acquired else "—",
    ]

    fig = go.Figure(
        go.Funnel(
            y=stages,
            x=counts,
            textposition="inside",
            textinfo="value+percent initial",
            marker=dict(color=["#1f6feb", "#388bfd", "#79c0ff"]),
            connector=dict(line=dict(color="rgba(100,100,100,0.3)", width=1)),
        )
    )
    fig.update_layout(
        title="Acquisition funnel — within-panel cohort",
        yaxis_title="",
        xaxis_title="Customers",
    )
    st.plotly_chart(fig, use_container_width=True)
    st.caption(
        "Denominator: customers whose acquisition month falls within the 17-month "
        "panel window (2015-01 to 2016-05). Left-censored customers (0.06%) excluded "
        "from adopted count. Retention is 3-month card retention after first adoption. "
        "'Retained 3m' is a lower bound — panel truncation at May 2016 limits "
        "late cohorts."
    )


# ── Visual 3: Cohort × segment heatmap ───────────────────────────────────────────
with heatmap_tab:
    hdf = load_cohort_heatmap()

    if hdf.empty:
        st.warning("No fully-observed cohort x segment cells found.")
    else:
        total_cells = len(hdf)
        st.caption(
            f"Showing {total_cells} cells — fully-observed cohorts only "
            "(acq_month + 6 months ≤ panel end 2016-05). "
            "Later cohorts are excluded to avoid presenting censored rates as final."
        )

        pivot = hdf.pivot_table(
            index="acq_month_label",
            columns="segmento",
            values="adoption_rate",
            aggfunc="mean",
        )
        pivot = pivot.sort_index()

        fig = px.imshow(
            pivot,
            labels={
                "x": "Segment",
                "y": "Acquisition cohort",
                "color": "Adoption rate",
            },
            color_continuous_scale="Blues",
            aspect="auto",
            text_auto=".1%",
            title="Card adoption rate by cohort × segment (fully-observed, msa_6+)",
        )
        fig.update_coloraxes(colorbar_tickformat=".0%")
        st.plotly_chart(fig, use_container_width=True)

        with st.expander("Raw data"):
            st.dataframe(
                hdf[
                    [
                        "acq_month_label",
                        "segmento",
                        "cohort_size",
                        "n_adopted",
                        "adoption_rate",
                        "n_right_censored",
                        "fully_observed_12",
                    ]
                ].sort_values(["acq_month_label", "segmento"]),
                hide_index=True,
                use_container_width=True,
            )
        st.caption(
            "Segment codes from Santander panel: '01 - TOP', '02 - PARTICULARES', "
            "'03 - UNIVERSITARIO', 'unknown' (NULL in source). "
            "Cells with fully_observed_12=true have 12 full panel months of observation."
        )


# ── Visual 4: Ask the copilot (reactive text-to-metric Q&A) ──────────────────────
# The copilot is a SEPARATE Cloud Run service (protobuf split). This tab is a thin client:
# it POSTs the question to its /ask endpoint, which runs the L2→L1→L3→L4 hardening gates
# before spending a Gemini token. Every answer is text-to-metric over the governed layer —
# never raw SQL — so the numbers match the charts above.
with copilot_tab:
    st.subheader("Ask the copilot")
    st.caption(
        "Reactive, single-agent Q&A over the same governed metrics the charts use "
        "(text-to-metric, never text-to-SQL). Deliberately minimal — the multi-agent work "
        "is the proactive digest above. Answers state WHAT the metrics show, not WHY."
    )

    if not COPILOT_API_URL:
        st.info(
            "The copilot API URL is not configured. Set `COPILOT_API_URL` (locally: run "
            "`make api` and export `COPILOT_API_URL=http://localhost:8000`). In the deployed "
            "cockpit this is wired to the copilot Cloud Run service automatically."
        )
    else:
        question = st.text_input(
            "Question",
            placeholder="e.g. What is the adoption_rate for the 2015-06 cohort at msa_6?",
        )
        if st.button("Ask", type="primary") and question.strip():
            with st.spinner("Thinking…"):
                try:
                    resp = requests.post(
                        f"{COPILOT_API_URL}/ask",
                        json={"question": question},
                        timeout=60,
                    )
                except requests.RequestException as exc:
                    st.error(f"Could not reach the copilot API: {exc}")
                else:
                    payload = resp.json() if resp.content else {}
                    if resp.status_code == 200:
                        st.markdown(payload.get("answer") or "_(empty answer)_")
                        if payload.get("cached"):
                            st.caption("Served from the answer cache — $0, no token spent.")
                    elif resp.status_code == 400:
                        st.warning(
                            "The question was rejected by the on-topic / input guard "
                            f"(reason: {payload.get('reason', 'rejected')}). Ask about the "
                            "governed funnel metrics — adoption, retention, cohorts, segments."
                        )
                    elif resp.status_code == 429:
                        st.warning("Rate limit reached — the free-tier guard is protecting the quota. Try again shortly.")
                    else:
                        st.error(f"Unexpected response ({resp.status_code}).")
